# fly.toml app configuration file generated for sse-lab-6o8dqg on 2026-08-24T13:41:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sse-lab-6o8dqg'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.25'

[env]
  PORT = '8080'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
